// Standardized API Response Types - Matching Backend Structure
// Following the 3 Core Types Principle from Backend API

// ## CORE PRINCIPLES - MUST FOLLOW STRICTLY
// ✅ Every response follows 3 core types: ApiResponse<T>, PaginatedApiResponse<T>, OperationResponse

// ### 1. RESPONSE TYPE MAPPING (Based on HTTP Method & Data Type)
// - GET single item: ApiResponse<T> - Always wrap single data items
// - GET collection with pagination: PaginatedApiResponse<T> - Data with pagination meta
// - POST/PUT/PATCH/DELETE operations: OperationResponse - Simple confirmation with optional ID

// ### 2. CONSISTENCY RULES
// - ALL successful responses MUST include: success=true, message, timestamp
// - ALL responses MUST be predictable - same structure for same operation types
// - Services should return FULL responses to preserve backend messages and metadata
// - Components can extract data when needed, but have access to full context

/**
 * Standard API response - for GET requests returning single items or non-paginated data
 * @template T - Type of the data being returned
 */
export interface ApiResponse<T = any> {
  success: boolean;
  message: string;
  data: T;
  timestamp: Date;
}

/**
 * Paginated API response - for GET requests returning collections with pagination
 */
export interface PaginatedApiResponse<T = any> {
  success: boolean;
  message: string;
  data: T[];
  pagination: PaginationMeta;
  timestamp: Date;
}

/**
 * Pagination metadata - matches backend structure exactly
 */
export interface PaginationMeta {
  page: number;
  limit: number;
  total: number;
  totalPages: number;
  hasNext: boolean;
  hasPrevious: boolean;
}

/**
 * Operation response - for all CUD operations (Create/Update/Delete)
 */
export interface OperationResponse {
  success: boolean;
  message: string;
  id?: number | string;
  timestamp: Date;
}

// ================================ Error Response Types ================================== //

/**
 * NestJS Standard Error Response - automatically generated by NestJS exceptions
 * This is what you'll receive for 4xx and 5xx errors
 */
export interface NestJSErrorResponse {
  statusCode: number;
  message: string | string[];
  error: string;
  timestamp?: string;
  path?: string;
}

// ==================================== Query Types ======================================= //

export enum OrderDirection {
  ASC = "ASC",
  DESC = "DESC",
}

export interface BaseQuery {
  page?: number;
  limit?: number;
  orderBy?: string;
  orderDirection?: OrderDirection;
}

// ========================== Type Guards for Response Validation ======================== //

/**
 * Type guard to check if response is ApiResponse
 */
export function isApiResponse<T>(response: any): response is ApiResponse<T> {
  return (
    typeof response === "object" &&
    response !== null &&
    typeof response.success === "boolean" &&
    typeof response.message === "string" &&
    "data" in response &&
    "timestamp" in response
  );
}

/**
 * Type guard to check if response is PaginatedApiResponse
 */
export function isPaginatedApiResponse<T>(
  response: any
): response is PaginatedApiResponse<T> {
  return (
    typeof response === "object" &&
    response !== null &&
    typeof response.success === "boolean" &&
    typeof response.message === "string" &&
    Array.isArray(response.data) &&
    "pagination" in response &&
    "timestamp" in response
  );
}

/**
 * Type guard to check if response is OperationResponse
 */
export function isOperationResponse(
  response: any
): response is OperationResponse {
  return (
    typeof response === "object" &&
    response !== null &&
    typeof response.success === "boolean" &&
    typeof response.message === "string" &&
    "timestamp" in response &&
    !("data" in response)
  );
}

/**
 * Type guard to check if response is NestJS error
 */
export function isNestJSError(response: any): response is NestJSErrorResponse {
  return (
    typeof response === "object" &&
    response !== null &&
    typeof response.statusCode === "number" &&
    (typeof response.message === "string" || Array.isArray(response.message)) &&
    typeof response.error === "string"
  );
}
